//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30319.42000
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuonKit.Validation {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class ErrorMessages {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ErrorMessages() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuonKit.Validation.ErrorMessages", typeof(ErrorMessages).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must be false.
		/// </summary>
		internal static string BeFalse {
			get {
				return ResourceManager.GetString("BeFalse", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must be true.
		/// </summary>
		internal static string BeTrue {
			get {
				return ResourceManager.GetString("BeTrue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must be between {arg0} and {arg2}.
		/// </summary>
		internal static string Between {
			get {
				return ResourceManager.GetString("Between", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must be the same as {arg0}.
		/// </summary>
		internal static string EqualTo {
			get {
				return ResourceManager.GetString("EqualTo", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must be greater than {arg0}.
		/// </summary>
		internal static string GreaterThan {
			get {
				return ResourceManager.GetString("GreaterThan", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must be greater than or equal to {arg0}.
		/// </summary>
		internal static string GreaterThanEq {
			get {
				return ResourceManager.GetString("GreaterThanEq", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must be less than {arg0}.
		/// </summary>
		internal static string LessThan {
			get {
				return ResourceManager.GetString("LessThan", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must be less than or equal to {arg0}.
		/// </summary>
		internal static string LessThanEq {
			get {
				return ResourceManager.GetString("LessThanEq", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must be at most {arg0} characters.
		/// </summary>
		internal static string MaxLength {
			get {
				return ResourceManager.GetString("MaxLength", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must be at least {0}.
		/// </summary>
		internal static string MinChars {
			get {
				return ResourceManager.GetString("MinChars", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must be at least {arg0} characters.
		/// </summary>
		internal static string MinLength {
			get {
				return ResourceManager.GetString("MinLength", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must contain at least one entry.
		/// </summary>
		internal static string NotEmpty {
			get {
				return ResourceManager.GetString("NotEmpty", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must not be the same as {arg0}.
		/// </summary>
		internal static string NotEqualTo {
			get {
				return ResourceManager.GetString("NotEqualTo", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Required.
		/// </summary>
		internal static string Required {
			get {
				return ResourceManager.GetString("Required", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must be a valid email address.
		/// </summary>
		internal static string ValidEmail {
			get {
				return ResourceManager.GetString("ValidEmail", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must be a valid postcode.
		/// </summary>
		internal static string ValidPostcode {
			get {
				return ResourceManager.GetString("ValidPostcode", resourceCulture);
			}
		}
	}
}
